table dCalendario
	lineageTag: 7899075d-46c8-4c43-94d7-f8d34a0e712e
	dataCategory: Time

	column Data
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: c8535bc1-7c68-4e0e-ae8d-06207cc9ed71
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Nome_Mes
		dataType: string
		lineageTag: f95f9aff-9c69-41c9-b591-547742285bb7
		summarizeBy: none
		sourceColumn: Nome_Mes

		annotation SummarizationSetBy = Automatic

	column Mes_Num
		dataType: int64
		formatString: 0
		lineageTag: c15e6b77-be18-400a-89ae-7796eedd52cc
		summarizeBy: sum
		sourceColumn: Mes_Num

		annotation SummarizationSetBy = Automatic

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: e16421dc-1351-4cc7-a7f3-cdc613dc6ae2
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	partition dCalendario = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(Caminho_Arquivos&"dCalendario.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Data", type date}, {"Nome_Mes", type text}, {"Mes_Num", Int64.Type}, {"Ano", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

